apiVersion: v1
kind: Service
metadata:
  name: deploy
  namespace: namespace-workflow-1718319361734
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: deploy
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000